# Generated by Django 4.0.7 on 2022-10-14 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("geo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания записи"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Время обновления записи"
                    ),
                ),
                ("source", models.CharField(max_length=50, verbose_name="Источник")),
                (
                    "author",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="Автор"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="Описание"),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=300,
                        verbose_name="Ссылка на источник",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(verbose_name="Дата и время публикации"),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="news_country",
                        to="geo.country",
                        verbose_name="Страна",
                    ),
                ),
            ],
            options={
                "verbose_name": "Новость",
                "verbose_name_plural": "Новости",
                "ordering": ["published_at"],
            },
        ),
    ]
