# Generated by Django 4.0.8 on 2022-11-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="region",
            field=models.CharField(blank=True, max_length=50, verbose_name="Регион"),
        ),
    ]
